name: Run Data Science Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # You can change this to match your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas 
        # Add any required packages here, e.g.:
        # pip install pandas numpy

    - name: Run test.py
      run: python Data_Science/test.py